%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.4.0

-ifndef(all_pb).
-define(all_pb, true).

-define(all_pb_gpb_version, "4.4.0").

-ifndef('M_1101_TOC_PB_H').
-define('M_1101_TOC_PB_H', true).
-record(m_1101_toc,
        {cmd                    :: non_neg_integer(), % = 1, 32 bits
         error_code             :: non_neg_integer(), % = 2, 32 bits
         description            :: iolist() | undefined % = 3
        }).
-endif.

-ifndef('M_1001_TOS_PB_H').
-define('M_1001_TOS_PB_H', true).
-record(m_1001_tos,
        {
        }).
-endif.

-ifndef('M_1001_TOC_PB_H').
-define('M_1001_TOC_PB_H', true).
-record(m_1001_toc,
        {time                   :: non_neg_integer() % = 1, 32 bits
        }).
-endif.

-ifndef('M_1002_TOS_PB_H').
-define('M_1002_TOS_PB_H', true).
-record(m_1002_tos,
        {
        }).
-endif.

-ifndef('M_1002_TOC_PB_H').
-define('M_1002_TOC_PB_H', true).
-record(m_1002_toc,
        {public_key             :: iodata()         % = 1
        }).
-endif.

-ifndef('M_1003_TOS_PB_H').
-define('M_1003_TOS_PB_H', true).
-record(m_1003_tos,
        {username               :: iolist(),        % = 1
         password               :: iolist()         % = 2
        }).
-endif.

-ifndef('M_1003_TOC_PB_H').
-define('M_1003_TOC_PB_H', true).
-record(m_1003_toc,
        {ip                     :: iolist(),        % = 1
         port                   :: iolist(),        % = 2
         role_id                :: non_neg_integer(), % = 3, 32 bits
         auth_key               :: iodata()         % = 4
        }).
-endif.

-ifndef('M_1004_TOC_PB_H').
-define('M_1004_TOC_PB_H', true).
-record(m_1004_toc,
        {ip                     :: iolist(),        % = 1
         role_id                :: non_neg_integer(), % = 2, 32 bits
         test_info = []         :: [all_pb:p_test()] | undefined % = 3
        }).
-endif.

-ifndef('M_1090_TOS_PB_H').
-define('M_1090_TOS_PB_H', true).
-record(m_1090_tos,
        {role_id                :: non_neg_integer(), % = 1, 32 bits
         auth_key               :: iodata()         % = 2
        }).
-endif.

-ifndef('M_1090_TOC_PB_H').
-define('M_1090_TOC_PB_H', true).
-record(m_1090_toc,
        {
        }).
-endif.

-ifndef('P_TEST_PB_H').
-define('P_TEST_PB_H', true).
-record(p_test,
        {ip                     :: iolist(),        % = 1
         role_id                :: non_neg_integer(), % = 2, 32 bits
         role_id3               :: non_neg_integer() | undefined, % = 3, 32 bits
         role_id4               :: iolist() | undefined, % = 4
         role_id5               :: non_neg_integer() | undefined % = 5, 32 bits
        }).
-endif.

-endif.
